name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: docker run
      run: |
          cd micro-ecommerce
          docker-compose up -d
      
    - name: Test container database
      run: |
          docker run --network container:ecommerce-database jwilder/dockerize -wait tcp://ecommerce-database:5432 -timeout 500s -wait-retry-interval 5s
      
    - name: Test container rabbitmq
      run: |
          docker run --network container:ecommerce-rabbitmq jwilder/dockerize -wait tcp://ecommerce-rabbitmq:15672 -timeout 500s -wait-retry-interval 5s
  
    - name: Test container app
      run: |
          docker run --network container:micro-ecommerce-app jwilder/dockerize -wait tcp://micro-ecommerce-app:8000 -timeout 500s -wait-retry-interval 5s

    - name: Run Tests
      run: |
        cd micro-ecommerce
        docker-compose exec app sh -c "pytest --disable-warnings"

    - name: Stop Docker Compose (Cleanup)
      if: always()
      run: |
        cd micro-ecommerce
        docker-compose down

    - name: Debugging Logs on Failure
      if: failure()
      run: |
        cd micro-ecommerce
        docker-compose logs
