name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Start Docker Compose
      run: |
        cd micro-ecommerce
        docker-compose up -d

    - name: Wait for database
      run: |
        docker-compose exec database sh -c "while ! nc -z database 5432; do sleep 1; done"
    
    - name: Wait for RabbitMQ
      run: |
        docker-compose exec rabbitmq sh -c "while ! nc -z rabbitmq 15672; do sleep 1; done"

    - name: Wait for app
      run: |
        docker-compose exec app sh -c "while ! nc -z app 8000; do sleep 1; done"

    - name: Stop Docker Compose (Cleanup)
      if: always()
      run: |
        docker-compose down
